Fix "API Update Required" notice due to deprecated BuildTarget.iPhone
The "API Update Required" popup is appearing on import, and `BuildTarget.iPhone` seems to be the cause:

    Assets/Editor/URLClient/URLClientPostprocessor.cs(38,31): error CS0619: `UnityEditor.BuildTarget.iPhone' is obsolete: `Use iOS instead (UnityUpgradable) -> iOS'